import type { Source } from "./types";

// 重构方案 §8.1 信源体系
// 注：Anthropic 已停更 RSS、机器之心 RSS 改为数据服务页、Papers With Code API 长期超时，
// 故这三者分别替换为 Google AI Blog / 雷锋网 / TechCrunch AI（均经实测可用）。
export const SOURCES: Source[] = [
  {
    id: "arxiv-ai",
    name: "arXiv (cs.AI / cs.CL / cs.LG / cs.CV)",
    type: "api",
    category: "paper",
    url: "http://export.arxiv.org/api/query",
    enabled: true,
    fetchInterval: 86_400,
  },
  {
    id: "github-trending",
    name: "GitHub Trending (AI/ML)",
    type: "scraper",
    category: "project",
    url: "https://github.com/trending",
    enabled: true,
    fetchInterval: 86_400,
  },
  {
    id: "hacker-news",
    name: "Hacker News",
    type: "api",
    category: "news",
    url: "https://hn.algolia.com/api/v1/search",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "36kr",
    name: "36氪",
    type: "rss",
    category: "news",
    url: "https://36kr.com/feed",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "qbitai",
    name: "量子位",
    type: "rss",
    category: "news",
    url: "https://www.qbitai.com/feed",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "openai-blog",
    name: "OpenAI Blog",
    type: "rss",
    category: "company",
    url: "https://openai.com/blog/rss.xml",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "google-ai",
    name: "Google AI Blog",
    type: "rss",
    category: "company",
    url: "https://blog.google/technology/ai/rss/",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "nvidia-blog",
    name: "NVIDIA Blog",
    type: "rss",
    category: "company",
    url: "https://blogs.nvidia.com/feed/",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "leiphone",
    name: "雷锋网 AI",
    type: "rss",
    category: "news",
    url: "https://www.leiphone.com/feed",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "techcrunch-ai",
    name: "TechCrunch AI",
    type: "rss",
    category: "news",
    url: "https://techcrunch.com/category/artificial-intelligence/feed/",
    enabled: true,
    fetchInterval: 3_600,
  },
  // ===== YouTube AI 频道（RSS，免 API Key）=====
  // 频道 ID 均经 qq_claw 实测解析，RSS 频道标题与 handle 吻合。
  {
    id: "yt-two-minute-papers",
    name: "Two Minute Papers",
    type: "youtube",
    category: "ai-video",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCbfYPyITQ-7l4upoX8nvctg",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "yt-yannic-kilcher",
    name: "Yannic Kilcher",
    type: "youtube",
    category: "ai-video",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCZHmQk67mSJgfCCTn7xBfew",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "yt-lex-fridman",
    name: "Lex Fridman",
    type: "youtube",
    category: "ai-video",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCSHZKyawb77ixDdsGog4iWA",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "yt-3blue1brown",
    name: "3Blue1Brown",
    type: "youtube",
    category: "ai-video",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCYO_jab_esuFRV4b17AJtAw",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "yt-deeplearning-ai",
    name: "DeepLearning.AI",
    type: "youtube",
    category: "ai-video",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCcIXc5mJsHVYTZR1maL5l9w",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "yt-sentdex",
    name: "sentdex",
    type: "youtube",
    category: "ai-video",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCfzlCWGWYyIQ0aLC5W48gBQ",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "yt-computerphile",
    name: "Computerphile",
    type: "youtube",
    category: "ai-video",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC9-y-6csu5WGm29I7JiwpnA",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "yt-nvidia",
    name: "NVIDIA",
    type: "youtube",
    category: "ai-video",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCHuiy8bXnmK5nisYHUd1J5g",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "yt-openai",
    name: "OpenAI",
    type: "youtube",
    category: "ai-video",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCXZCJLdBC09xxGZ6gcdrc6A",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "yt-google-developers",
    name: "Google for Developers",
    type: "youtube",
    category: "ai-video",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC_x5XG1OV2P6uZZ5FSM9Ttw",
    enabled: true,
    fetchInterval: 3_600,
  },
  // ===== Twitter/X AI 名人（xcancel RSS，需 Inoreader UA；见 fetchers.fetchTwitter）=====
  // 公共实例可能不稳定，失败不影响其它源；xcancel 封 UA 时整批失败需换 UA 或自建 RSSHub。
  {
    id: "tw-sama",
    name: "Sam Altman",
    type: "twitter",
    category: "news",
    url: "twitter/user/sama",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "tw-karpathy",
    name: "Andrej Karpathy",
    type: "twitter",
    category: "news",
    url: "twitter/user/karpathy",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "tw-ylecun",
    name: "Yann LeCun",
    type: "twitter",
    category: "news",
    url: "twitter/user/ylecun",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "tw-andrewyng",
    name: "Andrew Ng",
    type: "twitter",
    category: "news",
    url: "twitter/user/AndrewYNg",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "tw-fchollet",
    name: "François Chollet",
    type: "twitter",
    category: "news",
    url: "twitter/user/fchollet",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "tw-jasonwei",
    name: "Jason Wei",
    type: "twitter",
    category: "news",
    url: "twitter/user/_jasonwei",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "tw-drjimfan",
    name: "Jim Fan",
    type: "twitter",
    category: "news",
    url: "twitter/user/DrJimFan",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "tw-swyx",
    name: "swyx",
    type: "twitter",
    category: "news",
    url: "twitter/user/swyx",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "tw-hardmaru",
    name: "David Ha",
    type: "twitter",
    category: "news",
    url: "twitter/user/hardmaru",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "tw-goodfellow",
    name: "Ian Goodfellow",
    type: "twitter",
    category: "news",
    url: "twitter/user/goodfellow_ian",
    enabled: true,
    fetchInterval: 3_600,
  },
  // ===== X（Twitter）AI Agent 实践账号 —— 来自「AI-Agent 账号研究」，去重后追加 =====
  // 已存在的 karpathy / AndrewYNg / DrJimFan / swyx 不重复添加。
  // 框架与官方
  {
    id: "tw-hwchase17",
    name: "Harrison Chase (LangChain)",
    type: "twitter",
    category: "news",
    url: "twitter/user/hwchase17",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "tw-langchain",
    name: "LangChain",
    type: "twitter",
    category: "news",
    url: "twitter/user/LangChainAI",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "tw-jerryjliu0",
    name: "Jerry Liu (LlamaIndex)",
    type: "twitter",
    category: "news",
    url: "twitter/user/jerryjliu0",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "tw-huggingface",
    name: "Hugging Face",
    type: "twitter",
    category: "news",
    url: "twitter/user/huggingface",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "tw-clementdelangue",
    name: "Clément Delangue",
    type: "twitter",
    category: "news",
    url: "twitter/user/ClementDelangue",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "tw-anthropic",
    name: "Anthropic",
    type: "twitter",
    category: "news",
    url: "twitter/user/AnthropicAI",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "tw-alexalbert",
    name: "Alex Albert (Anthropic)",
    type: "twitter",
    category: "news",
    url: "twitter/user/alexalbert__",
    enabled: true,
    fetchInterval: 3_600,
  },
  // 动手派工程师
  {
    id: "tw-simonw",
    name: "Simon Willison",
    type: "twitter",
    category: "news",
    url: "twitter/user/simonw",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "tw-goodside",
    name: "Riley Goodside",
    type: "twitter",
    category: "news",
    url: "twitter/user/goodside",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "tw-hamelhusain",
    name: "Hamel Husain",
    type: "twitter",
    category: "news",
    url: "twitter/user/HamelHusain",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "tw-cobusgreyling",
    name: "Cobus Greyling",
    type: "twitter",
    category: "news",
    url: "twitter/user/CobusGreyling",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "tw-carmack",
    name: "John Carmack",
    type: "twitter",
    category: "news",
    url: "twitter/user/ID_AA_Carmack",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "tw-dvirb",
    name: "Dvir Borenstein",
    type: "twitter",
    category: "news",
    url: "twitter/user/dvirb",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "tw-dotey",
    name: "宝玉 (dotey)",
    type: "twitter",
    category: "news",
    url: "twitter/user/dotey",
    enabled: true,
    fetchInterval: 3_600,
  },
  // 工具与技巧流
  {
    id: "tw-mreflow",
    name: "Matt Wolfe",
    type: "twitter",
    category: "news",
    url: "twitter/user/mreflow",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "tw-therundownai",
    name: "The Rundown AI",
    type: "twitter",
    category: "news",
    url: "twitter/user/TheRundownAI",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "tw-rasbt",
    name: "Sebastian Raschka",
    type: "twitter",
    category: "news",
    url: "twitter/user/rasbt",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "tw-alliekmiller",
    name: "Allie K. Miller",
    type: "twitter",
    category: "news",
    url: "twitter/user/alliekmiller",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "tw-tibomaker",
    name: "tibo_maker",
    type: "twitter",
    category: "news",
    url: "twitter/user/tibo_maker",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "tw-linusekenstam",
    name: "Linus Ekenstam",
    type: "twitter",
    category: "news",
    url: "twitter/user/LinusEkenstam",
    enabled: true,
    fetchInterval: 3_600,
  },
  // TPOT 高信噪比圈层
  {
    id: "tw-andrewcurran",
    name: "Andrew Curran",
    type: "twitter",
    category: "news",
    url: "twitter/user/AndrewCurran_",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "tw-flavioad",
    name: "flavioAd",
    type: "twitter",
    category: "news",
    url: "twitter/user/flavioAd",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "tw-fofrai",
    name: "fofr",
    type: "twitter",
    category: "news",
    url: "twitter/user/fofrAI",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "tw-emollick",
    name: "Ethan Mollick",
    type: "twitter",
    category: "news",
    url: "twitter/user/emollick",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "tw-teknium",
    name: "Teknium",
    type: "twitter",
    category: "news",
    url: "twitter/user/Teknium",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "tw-elderplinius",
    name: "Pliny the Liberator",
    type: "twitter",
    category: "news",
    url: "twitter/user/elder_plinius",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "tw-btibor91",
    name: "Tibor Blaho",
    type: "twitter",
    category: "news",
    url: "twitter/user/btibor91",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "tw-koltregaskes",
    name: "Kol Tregaskes",
    type: "twitter",
    category: "news",
    url: "twitter/user/koltregaskes",
    enabled: true,
    fetchInterval: 3_600,
  },
  // ===== 微博 AI/科技大 V（自建 RSSHub，路由 /weibo/user/{uid}，需数字 UID）=====
  // 数字 UID 经联网核验；量子位已有 RSS 源(qbitai)不重复收录；
  // 李继刚 / 云中江树（自定义域名、数字 UID 被登录墙隐藏）与 orangeAGI（疑无微博）暂未收录。
  {
    id: "wb-baoyu",
    name: "宝玉xp",
    type: "weibo",
    category: "news",
    url: "weibo/user/1727858283",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "wb-aikeke",
    name: "爱可可-爱生活",
    type: "weibo",
    category: "news",
    url: "weibo/user/1402400261",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "wb-guizang",
    name: "归藏的AI工具箱",
    type: "weibo",
    category: "news",
    url: "weibo/user/6182606334",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "wb-qiuzhi",
    name: "秋芝2046",
    type: "weibo",
    category: "news",
    url: "weibo/user/7892977403",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "wb-kazki",
    name: "数字生命卡兹克",
    type: "weibo",
    category: "news",
    url: "weibo/user/5700099573",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "wb-linyi",
    name: "林亦LYi",
    type: "weibo",
    category: "news",
    url: "weibo/user/6444741184",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "wb-fusheng",
    name: "傅盛",
    type: "weibo",
    category: "news",
    url: "weibo/user/1554710050",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "wb-awen",
    name: "Simon_阿文",
    type: "weibo",
    category: "news",
    url: "weibo/user/1757693565",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "wb-xiangyang",
    name: "向阳乔木",
    type: "weibo",
    category: "news",
    url: "weibo/user/1620605960",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "wb-jihuicheng",
    name: "纪慧诚",
    type: "weibo",
    category: "news",
    url: "weibo/user/1840422660",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "wb-dagu",
    name: "大谷Spitzer",
    type: "weibo",
    category: "news",
    url: "weibo/user/2395607675",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "wb-huangjian",
    name: "黄建同学",
    type: "weibo",
    category: "news",
    url: "weibo/user/5648162302",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "wb-yuboshi",
    name: "北大AI鱼博士",
    type: "weibo",
    category: "news",
    url: "weibo/user/1644054135",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "wb-weiboai",
    name: "微博AI",
    type: "weibo",
    category: "news",
    url: "weibo/user/5777227559",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "wb-hlw",
    name: "互联网的那点事",
    type: "weibo",
    category: "news",
    url: "weibo/user/1627825392",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "wb-aiyanxi",
    name: "AI研习社",
    type: "weibo",
    category: "news",
    url: "weibo/user/6811179912",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "wb-geekpark",
    name: "极客公园",
    type: "weibo",
    category: "news",
    url: "weibo/user/1735559201",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "wb-zhouhongyi",
    name: "周鸿祎",
    type: "weibo",
    category: "news",
    url: "weibo/user/1708942053",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "wb-wangyonggang",
    name: "王咏刚",
    type: "weibo",
    category: "news",
    url: "weibo/user/1642051827",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "wb-laoshimu",
    name: "老师木",
    type: "weibo",
    category: "news",
    url: "weibo/user/1991303247",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "wb-aigclink",
    name: "AIGCLINK",
    type: "weibo",
    category: "news",
    url: "weibo/user/3894431038",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "wb-turingcat",
    name: "图灵的猫",
    type: "weibo",
    category: "news",
    url: "weibo/user/7400905898",
    enabled: true,
    fetchInterval: 3_600,
  },
];

export function getSource(name: string): Source | undefined {
  return SOURCES.find((s) => s.name === name);
}
