import type { Source } from "./types";

// 重构方案 §8.1 信源体系
// 注：Anthropic 已停更 RSS、机器之心 RSS 改为数据服务页、Papers With Code API 长期超时，
// 故这三者分别替换为 Google AI Blog / 雷锋网 / TechCrunch AI（均经实测可用）。
export const SOURCES: Source[] = [
  {
    id: "arxiv-ai",
    name: "arXiv (cs.AI / cs.CL / cs.LG / cs.CV)",
    type: "api",
    category: "paper",
    url: "http://export.arxiv.org/api/query",
    enabled: true,
    fetchInterval: 86_400,
  },
  {
    id: "github-trending",
    name: "GitHub Trending (AI/ML)",
    type: "scraper",
    category: "project",
    url: "https://github.com/trending",
    enabled: true,
    fetchInterval: 86_400,
  },
  {
    id: "hacker-news",
    name: "Hacker News",
    type: "api",
    category: "news",
    url: "https://hn.algolia.com/api/v1/search",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "36kr",
    name: "36氪",
    type: "rss",
    category: "news",
    url: "https://36kr.com/feed",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "qbitai",
    name: "量子位",
    type: "rss",
    category: "news",
    url: "https://www.qbitai.com/feed",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "openai-blog",
    name: "OpenAI Blog",
    type: "rss",
    category: "company",
    url: "https://openai.com/blog/rss.xml",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "google-ai",
    name: "Google AI Blog",
    type: "rss",
    category: "company",
    url: "https://blog.google/technology/ai/rss/",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "nvidia-blog",
    name: "NVIDIA Blog",
    type: "rss",
    category: "company",
    url: "https://blogs.nvidia.com/feed/",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "leiphone",
    name: "雷锋网 AI",
    type: "rss",
    category: "news",
    url: "https://www.leiphone.com/feed",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "techcrunch-ai",
    name: "TechCrunch AI",
    type: "rss",
    category: "news",
    url: "https://techcrunch.com/category/artificial-intelligence/feed/",
    enabled: true,
    fetchInterval: 3_600,
  },
  // ===== YouTube AI 频道（RSS，免 API Key）=====
  // 频道 ID 均经 qq_claw 实测解析，RSS 频道标题与 handle 吻合。
  {
    id: "yt-two-minute-papers",
    name: "Two Minute Papers",
    type: "youtube",
    category: "ai-video",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCbfYPyITQ-7l4upoX8nvctg",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "yt-yannic-kilcher",
    name: "Yannic Kilcher",
    type: "youtube",
    category: "ai-video",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCZHmQk67mSJgfCCTn7xBfew",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "yt-lex-fridman",
    name: "Lex Fridman",
    type: "youtube",
    category: "ai-video",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCSHZKyawb77ixDdsGog4iWA",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "yt-3blue1brown",
    name: "3Blue1Brown",
    type: "youtube",
    category: "ai-video",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCYO_jab_esuFRV4b17AJtAw",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "yt-deeplearning-ai",
    name: "DeepLearning.AI",
    type: "youtube",
    category: "ai-video",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCcIXc5mJsHVYTZR1maL5l9w",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "yt-sentdex",
    name: "sentdex",
    type: "youtube",
    category: "ai-video",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCfzlCWGWYyIQ0aLC5W48gBQ",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "yt-computerphile",
    name: "Computerphile",
    type: "youtube",
    category: "ai-video",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC9-y-6csu5WGm29I7JiwpnA",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "yt-nvidia",
    name: "NVIDIA",
    type: "youtube",
    category: "ai-video",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCHuiy8bXnmK5nisYHUd1J5g",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "yt-openai",
    name: "OpenAI",
    type: "youtube",
    category: "ai-video",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCXZCJLdBC09xxGZ6gcdrc6A",
    enabled: true,
    fetchInterval: 3_600,
  },
  {
    id: "yt-google-developers",
    name: "Google for Developers",
    type: "youtube",
    category: "ai-video",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC_x5XG1OV2P6uZZ5FSM9Ttw",
    enabled: true,
    fetchInterval: 3_600,
  },
];

export function getSource(name: string): Source | undefined {
  return SOURCES.find((s) => s.name === name);
}
