import type { Item, Category } from "../types";
import { computeScore } from "../scoring";
import { SITE } from "../config";

// ---- 时间工具：以"现在"为基准确定性生成日期，保证可复现 ----
const NOW = Date.now();
const DAY = 86_400_000;
function at(offsetDays: number, hour = 9, min = 0): string {
  const d = new Date(NOW - offsetDays * DAY);
  d.setHours(hour, min, 0, 0);
  return d.toISOString();
}
function ymd(offsetDays: number): string {
  return new Date(NOW - offsetDays * DAY).toISOString().slice(0, 10);
}

// ---- 分类体系（重构方案 §13 优点10：按类型+领域组织）----
export const CATEGORIES: Category[] = [
  { slug: "generative-ai", label: "生成式 AI", type: "paper", description: "图像、视频、音频与文本生成" },
  { slug: "agent", label: "Agent / 智能体", type: "paper", description: "自主智能体、工具调用与规划" },
  { slug: "multimodal", label: "多模态", type: "paper", description: "跨模态理解与生成" },
  { slug: "vision", label: "计算机视觉", type: "paper", description: "检测、分割与识别" },
  { slug: "nlp", label: "自然语言处理", type: "paper", description: "大模型、推理与对齐" },
  { slug: "rl", label: "强化学习", type: "paper", description: "策略优化与决策" },
  { slug: "security", label: "AI 安全", type: "paper", description: "对齐、鲁棒性与隐私" },
  { slug: "coding", label: "编程助手", type: "project", description: "代码生成与工程化" },
  { slug: "company", label: "公司与产品", type: "news", description: "厂商动态与新品" },
  { slug: "policy", label: "政策与监管", type: "news", description: "法规与治理" },
  { slug: "research", label: "研究进展", type: "news", description: "学界与业界突破" },
];

interface Raw {
  type: Item["type"];
  title: string;
  title_zh?: string;
  summary: string;
  recommendation?: string;
  url: string;
  source: string;
  sources: string[];
  category: string;
  tags: string[];
  offset: number; // 距今天数
  hour?: number;
  sel?: boolean; // 是否精选（默认 true）
  paper?: Item["paperFields"];
  project?: Item["projectFields"];
  news?: Item["newsFields"];
}

const RAW: Raw[] = [
  // ===== 第 0 天（今天）=====
  {
    type: "paper",
    title: "AlayaWorld: Long-Horizon Interactive Video World Generation",
    title_zh: "可交互长时序视频世界生成模型",
    summary:
      "提出一种支持用户实时交互的长时序视频世界模型，可在数千帧尺度上保持一致性与可控性，适用于游戏与仿真场景。",
    recommendation: "长时序一致性是视频生成的关键瓶颈，该工作把交互控制引入世界模型，值得关注。",
    url: "https://arxiv.org/abs/2607.06291",
    source: "arXiv",
    sources: ["arXiv", "Hacker News"],
    category: "generative-ai",
    tags: ["视频生成", "虚拟环境", "游戏AI"],
    offset: 0,
    hour: 8,
    paper: {
      arxivId: "2607.06291",
      authors: ["Wei Zhang", "Lin Chen", "Hao Yu"],
      domains: ["cs.CV", "cs.AI"],
      pdfUrl: "https://arxiv.org/pdf/2607.06291",
    },
  },
  {
    type: "project",
    title: "openclaw/agent-kit",
    summary: "轻量级 Agent 编排框架，内置工具注册、记忆与可观测性，支持本地与云端混合执行。",
    recommendation: "相比 LangChain 更轻，适合嵌入式场景，本周星标增长迅猛。",
    url: "https://github.com/openclaw/agent-kit",
    source: "GitHub",
    sources: ["GitHub", "Hacker News"],
    category: "coding",
    tags: ["Agent", "开源", "框架"],
    offset: 0,
    hour: 7,
    project: {
      repo: "openclaw/agent-kit",
      language: "Python",
      stars: 18400,
      todayStars: 1620,
      license: "Apache-2.0",
    },
  },
  {
    type: "news",
    title: "某头部厂商发布新一代多模态旗舰模型",
    summary: "新模型在长上下文与实时语音交互上大幅提升，并开放了更低成本的 API 档位。",
    recommendation: "价格下探将加速多模态应用落地，关注其对开发者生态的影响。",
    url: "https://www.jiqizhixin.com/articles/xyz",
    source: "机器之心",
    sources: ["机器之心", "量子位", "36氪"],
    category: "company",
    tags: ["大模型", "多模态", "API"],
    offset: 0,
    hour: 9,
    news: { sourceUrls: ["https://www.jiqizhixin.com/articles/xyz", "https://www.qbitai.com/p/abc"] },
  },
  {
    type: "paper",
    title: "Self-Correcting Reasoning via Verifier-Guided Tree Search",
    title_zh: "基于验证器引导树搜索的自纠错推理",
    summary: "引入可微验证器在推理树中剪枝并回溯，在数学与代码任务上显著优于单次采样。",
    url: "https://arxiv.org/abs/2607.06110",
    source: "arXiv",
    sources: ["arXiv"],
    category: "nlp",
    tags: ["推理", "强化学习", "大模型"],
    offset: 0,
    hour: 10,
    paper: {
      arxivId: "2607.06110",
      authors: ["Ming Li", "Sara König"],
      domains: ["cs.CL", "cs.AI"],
      pdfUrl: "https://arxiv.org/pdf/2607.06110",
    },
  },
  {
    type: "project",
    title: "silverfox/tts-fast",
    summary: "超低延迟流式语音合成引擎，CPU 实时率 < 0.3，支持中英文混合与情感控制。",
    url: "https://github.com/silverfox/tts-fast",
    source: "GitHub",
    sources: ["GitHub"],
    category: "multimodal",
    tags: ["语音", "开源", "推理"],
    offset: 0,
    hour: 11,
    project: {
      repo: "silverfox/tts-fast",
      language: "Rust",
      stars: 9200,
      todayStars: 540,
      license: "MIT",
    },
  },
  {
    type: "news",
    title: "欧盟就通用 AI 模型透明度义务发布最终指南",
    summary: "指南明确了训练数据披露、风险评估与文档留存的具体要求，将于下季度生效。",
    url: "https://www.qbitai.com/p/eu",
    source: "量子位",
    sources: ["量子位", "36氪"],
    category: "policy",
    tags: ["监管", "合规", "大模型"],
    offset: 0,
    hour: 12,
    news: { sourceUrls: ["https://www.qbitai.com/p/eu"] },
  },

  // ===== 第 1 天 =====
  {
    type: "paper",
    title: "Sparse Mixture-of-Depths for Efficient Long-Context LLMs",
    title_zh: "面向长上下文大模型的稀疏混合深度架构",
    summary: "提出按 token 动态分配计算深度的稀疏结构，在 128K 上下文下将推理算力降低 40%。",
    recommendation: "长上下文的成本问题日益突出，动态计算分配是务实的优化方向。",
    url: "https://arxiv.org/abs/2607.05201",
    source: "arXiv",
    sources: ["arXiv", "Papers With Code"],
    category: "nlp",
    tags: ["长上下文", "大模型", "效率"],
    offset: 1,
    hour: 9,
    paper: {
      arxivId: "2607.05201",
      authors: ["Jin Park", "Yuki Tanaka"],
      domains: ["cs.CL"],
      pdfUrl: "https://arxiv.org/pdf/2607.05201",
    },
  },
  {
    type: "project",
    title: "nebula-labs/vectordb-lite",
    summary: "嵌入式向量数据库，单文件零依赖，支持量化索引与本地持久化，适合端侧 RAG。",
    url: "https://github.com/nebula-labs/vectordb-lite",
    source: "GitHub",
    sources: ["GitHub", "Hacker News"],
    category: "coding",
    tags: ["RAG", "开源", "向量库"],
    offset: 1,
    hour: 8,
    project: {
      repo: "nebula-labs/vectordb-lite",
      language: "Go",
      stars: 26700,
      todayStars: 2100,
      license: "BSD-3",
    },
  },
  {
    type: "news",
    title: "开源社区发布统一 Agent 协议草案",
    summary: "多家机构联合提出跨框架的 Agent 通信协议，目标是打通工具与记忆的互操作。",
    url: "https://www.jiqizhixin.com/articles/proto",
    source: "机器之心",
    sources: ["机器之心", "Hacker News"],
    category: "research",
    tags: ["Agent", "协议", "开源"],
    offset: 1,
    hour: 11,
    news: { sourceUrls: ["https://www.jiqizhixin.com/articles/proto"] },
  },
  {
    type: "paper",
    title: "Embodied Navigation with Vision-Language-Action Diffusion",
    title_zh: "基于视觉-语言-动作扩散模型的具身导航",
    summary: "将扩散模型用于连续动作空间的具身导航，在仿真基准上显著提升成功率与样本效率。",
    url: "https://arxiv.org/abs/2607.05012",
    source: "arXiv",
    sources: ["arXiv"],
    category: "vision",
    tags: ["具身智能", "扩散模型", "机器人"],
    offset: 1,
    hour: 13,
    paper: {
      arxivId: "2607.05012",
      authors: ["Chen Wu", "Aisha Rahman"],
      domains: ["cs.RO", "cs.CV"],
      pdfUrl: "https://arxiv.org/pdf/2607.05012",
    },
  },
  {
    type: "project",
    title: "brightAI/diffpaint",
    summary: "可控图像修复与重绘工具，支持指令驱动的局部编辑与风格迁移，提供 WebUI 与 API。",
    url: "https://github.com/brightAI/diffpaint",
    source: "GitHub",
    sources: ["GitHub"],
    category: "multimodal",
    tags: ["图像生成", "开源", "编辑"],
    offset: 1,
    hour: 14,
    project: {
      repo: "brightAI/diffpaint",
      language: "Python",
      stars: 14300,
      todayStars: 880,
      license: "Apache-2.0",
    },
  },
  {
    type: "news",
    title: "某云厂商上线一站式模型微调平台",
    summary: "平台提供数据清洗、训练、评测与部署流水线，按用量计费，降低中小企业微调门槛。",
    url: "https://www.36kr.com/p/cloud",
    source: "36氪",
    sources: ["36氪", "量子位"],
    category: "company",
    tags: ["微调", "云平台", "MLOps"],
    offset: 1,
    hour: 15,
    news: { sourceUrls: ["https://www.36kr.com/p/cloud"] },
  },

  // ===== 第 2 天 =====
  {
    type: "paper",
    title: "Instruction Following under Distribution Shift",
    title_zh: "分布偏移下的指令跟随鲁棒性研究",
    summary: "系统评估大模型在分布偏移场景中的指令遵循能力，并提出基于自一致性校准的缓解方法。",
    url: "https://arxiv.org/abs/2607.04188",
    source: "arXiv",
    sources: ["arXiv", "Papers With Code"],
    category: "nlp",
    tags: ["对齐", "鲁棒性", "大模型"],
    offset: 2,
    hour: 9,
    paper: {
      arxivId: "2607.04188",
      authors: ["Olga Petrova", "Dawei Liu"],
      domains: ["cs.CL", "cs.LG"],
      pdfUrl: "https://arxiv.org/pdf/2607.04188",
    },
  },
  {
    type: "project",
    title: "codepilot-local/refactor",
    summary: "完全本地运行的代码重构助手，基于小模型与静态分析，无需联网即可完成重命名与提取。",
    url: "https://github.com/codepilot-local/refactor",
    source: "GitHub",
    sources: ["GitHub", "Hacker News"],
    category: "coding",
    tags: ["编程", "开源", "本地"],
    offset: 2,
    hour: 10,
    project: {
      repo: "codepilot-local/refactor",
      language: "TypeScript",
      stars: 7100,
      todayStars: 410,
      license: "MIT",
    },
  },
  {
    type: "news",
    title: "研究揭示大模型记忆污染风险",
    summary: "实验表明训练数据中的重复与对抗样本会渗透到生成结果，呼吁更严格的数据治理。",
    url: "https://www.qbitai.com/p/mem",
    source: "量子位",
    sources: ["量子位", "机器之心"],
    category: "security",
    tags: ["AI安全", "数据治理", "对齐"],
    offset: 2,
    hour: 12,
    news: { sourceUrls: ["https://www.qbitai.com/p/mem"] },
  },
  {
    type: "paper",
    title: "Unified Multimodal Pretraining with Discrete Tokens",
    title_zh: "基于离散词元的统一多模态预训练",
    summary: "将图像、音频、文本统一为离散词元序列进行联合预训练，在多项下游任务上表现优异。",
    url: "https://arxiv.org/abs/2607.03990",
    source: "arXiv",
    sources: ["arXiv"],
    category: "multimodal",
    tags: ["多模态", "预训练", "统一架构"],
    offset: 2,
    hour: 14,
    paper: {
      arxivId: "2607.03990",
      authors: ["Hiroshi Sato", "Elena Rossi"],
      domains: ["cs.CV", "cs.CL"],
      pdfUrl: "https://arxiv.org/pdf/2607.03990",
    },
  },
  {
    type: "project",
    title: "deeproot/trainer",
    summary: "分布式训练框架，原生支持 MoE 与 3D 并行，提供细粒度 profiler 与故障自愈。",
    url: "https://github.com/deeproot/trainer",
    source: "GitHub",
    sources: ["GitHub"],
    category: "coding",
    tags: ["训练", "开源", "MoE"],
    offset: 2,
    hour: 15,
    project: {
      repo: "deeproot/trainer",
      language: "Python",
      stars: 33800,
      todayStars: 1300,
      license: "Apache-2.0",
    },
  },
  {
    type: "news",
    title: "自动驾驶公司公布端到端大模型路测数据",
    summary: "公开百万公里脱手驾驶数据，强调世界模型在长尾场景中的关键作用。",
    url: "https://www.jiqizhixin.com/articles/av",
    source: "机器之心",
    sources: ["机器之心", "36氪"],
    category: "research",
    tags: ["自动驾驶", "世界模型", "端到端"],
    offset: 2,
    hour: 16,
    news: { sourceUrls: ["https://www.jiqizhixin.com/articles/av"] },
  },

  // ===== 第 3 天 =====
  {
    type: "paper",
    title: "Reward Modeling without Human Preferences",
    title_zh: "无人类偏好的奖励建模",
    summary: "提出基于可验证信号的自动化奖励建模方法，在代码与数学任务上逼近人类偏好效果。",
    url: "https://arxiv.org/abs/2607.03011",
    source: "arXiv",
    sources: ["arXiv", "Papers With Code"],
    category: "rl",
    tags: ["强化学习", "奖励建模", "对齐"],
    offset: 3,
    hour: 9,
    paper: {
      arxivId: "2607.03011",
      authors: ["Fatima Noor", "Kevin Zhao"],
      domains: ["cs.LG", "cs.AI"],
      pdfUrl: "https://arxiv.org/pdf/2607.03011",
    },
  },
  {
    type: "project",
    title: "lumen-ai/rag-studio",
    summary: "可视化 RAG 编排工具，支持多路召回、重排与效果评估，导出为可部署流水线。",
    url: "https://github.com/lumen-ai/rag-studio",
    source: "GitHub",
    sources: ["GitHub", "Hacker News"],
    category: "coding",
    tags: ["RAG", "开源", "工作流"],
    offset: 3,
    hour: 10,
    project: {
      repo: "lumen-ai/rag-studio",
      language: "TypeScript",
      stars: 11900,
      todayStars: 720,
      license: "MIT",
    },
  },
  {
    type: "news",
    title: "芯片厂商推出面向推理的专用加速卡",
    summary: "新加速卡针对稀疏注意力与量化推理优化，标称能效较上代提升 2.5 倍。",
    url: "https://www.36kr.com/p/chip",
    source: "36氪",
    sources: ["36氪", "量子位"],
    category: "company",
    tags: ["芯片", "推理", "算力"],
    offset: 3,
    hour: 12,
    news: { sourceUrls: ["https://www.36kr.com/p/chip"] },
  },
  {
    type: "paper",
    title: "Audio-Visual Scene Understanding at Scale",
    title_zh: "大规模音视频场景理解",
    summary: "构建百万级音视频配对数据集，并训练统一模型完成事件检测与跨模态检索。",
    url: "https://arxiv.org/abs/2607.02877",
    source: "arXiv",
    sources: ["arXiv"],
    category: "vision",
    tags: ["多模态", "音频", "数据集"],
    offset: 3,
    hour: 14,
    paper: {
      arxivId: "2607.02877",
      authors: ["Marco Bianchi", "Yara Haddad"],
      domains: ["cs.CV", "cs.SD"],
      pdfUrl: "https://arxiv.org/pdf/2607.02877",
    },
  },
  {
    type: "project",
    title: "quanta/edge-llm",
    summary: "面向端侧设备的量化推理运行时，2GB 内存即可运行 7B 模型，支持 NPU 加速。",
    url: "https://github.com/quanta/edge-llm",
    source: "GitHub",
    sources: ["GitHub"],
    category: "coding",
    tags: ["端侧", "开源", "量化"],
    offset: 3,
    hour: 15,
    project: {
      repo: "quanta/edge-llm",
      language: "C++",
      stars: 20100,
      todayStars: 960,
      license: "Apache-2.0",
    },
  },
  {
    type: "news",
    title: "开源大模型社区发布多语言评测基准",
    summary: "基准覆盖 50 种语言的能力评测，揭示低资源语言上的显著性能差距。",
    url: "https://www.jiqizhixin.com/articles/bench",
    source: "机器之心",
    sources: ["机器之心", "Hacker News"],
    category: "research",
    tags: ["评测", "多语言", "开源"],
    offset: 3,
    hour: 16,
    news: { sourceUrls: ["https://www.jiqizhixin.com/articles/bench"] },
  },

  // ===== 第 4 天 =====
  {
    type: "paper",
    title: "Theory of Mind Emerges in Tool-Using Agents",
    title_zh: "工具使用智能体中涌现的心智理论能力",
    summary: "实验显示具备工具调用的智能体自发形成对「他者」信念的建模，提示社会推理的可塑性。",
    url: "https://arxiv.org/abs/2607.02033",
    source: "arXiv",
    sources: ["arXiv", "Papers With Code"],
    category: "agent",
    tags: ["Agent", "心智理论", "社会推理"],
    offset: 4,
    hour: 9,
    paper: {
      arxivId: "2607.02033",
      authors: ["Sofia Marin", "Tao Xu"],
      domains: ["cs.AI", "cs.CL"],
      pdfUrl: "https://arxiv.org/pdf/2607.02033",
    },
  },
  {
    type: "project",
    title: "forge-io/pipeline",
    summary: "数据到部署的 ML 流水线引擎，声明式配置，内置缓存与血缘追踪。",
    url: "https://github.com/forge-io/pipeline",
    source: "GitHub",
    sources: ["GitHub", "Hacker News"],
    category: "coding",
    tags: ["MLOps", "开源", "流水线"],
    offset: 4,
    hour: 10,
    project: {
      repo: "forge-io/pipeline",
      language: "Python",
      stars: 8800,
      todayStars: 350,
      license: "MIT",
    },
  },
  {
    type: "news",
    title: "监管机构就生成内容水印征询意见",
    summary: "草案要求公开分发的 AI 生成内容携带不可见水印，并设立违规举报通道。",
    url: "https://www.qbitai.com/p/wm",
    source: "量子位",
    sources: ["量子位", "36氪"],
    category: "policy",
    tags: ["监管", "水印", "合规"],
    offset: 4,
    hour: 12,
    news: { sourceUrls: ["https://www.qbitai.com/p/wm"] },
  },
  {
    type: "paper",
    title: "Continual Learning without Forgetting via Sparse Subnets",
    title_zh: "基于稀疏子网的免遗忘持续学习",
    summary: "为每个任务分配稀疏子网络，在保持旧任务性能的同时高效吸收新知识。",
    url: "https://arxiv.org/abs/2607.01880",
    source: "arXiv",
    sources: ["arXiv"],
    category: "rl",
    tags: ["持续学习", "鲁棒性", "效率"],
    offset: 4,
    hour: 14,
    paper: {
      arxivId: "2607.01880",
      authors: ["Priya Nair", "Lucas Meyer"],
      domains: ["cs.LG"],
      pdfUrl: "https://arxiv.org/pdf/2607.01880",
    },
  },
  {
    type: "project",
    title: "aurora-labs/speech-command",
    summary: "离线语音指令识别库，毫秒级唤醒，支持自定义热词与噪声鲁棒训练。",
    url: "https://github.com/aurora-labs/speech-command",
    source: "GitHub",
    sources: ["GitHub"],
    category: "multimodal",
    tags: ["语音", "开源", "端侧"],
    offset: 4,
    hour: 15,
    project: {
      repo: "aurora-labs/speech-command",
      language: "C",
      stars: 5600,
      todayStars: 220,
      license: "BSD-3",
    },
  },
  {
    type: "news",
    title: "学术会议录用率创历史新低",
    summary: "顶会投稿量同比翻倍，审稿人短缺导致录用率跌至 18%，引发对评审体系的讨论。",
    url: "https://www.jiqizhixin.com/articles/conf",
    source: "机器之心",
    sources: ["机器之心"],
    category: "research",
    tags: ["学术", "评测", "社区"],
    offset: 4,
    hour: 16,
    news: { sourceUrls: ["https://www.jiqizhixin.com/articles/conf"] },
  },
];

function build(): Item[] {
  return RAW.map((r, i) => {
    const id = `item_${(i + 1).toString().padStart(4, "0")}`;
    const publishedAt = at(r.offset, r.hour ?? 9);
    const selected = r.sel ?? true;
    const base: Item = {
      id,
      type: r.type,
      title: r.title,
      title_zh: r.title_zh,
      summary: r.summary,
      recommendation: r.recommendation,
      url: r.url,
      permalink: `${SITE.url}/items/${id}`,
      source: r.source,
      sources: r.sources,
      publishedAt,
      collectedAt: publishedAt,
      category: r.category,
      tags: r.tags,
      score: 0, // 下方计算
      selected,
      dailyDate: ymd(r.offset),
      attribution: { source: "hackcv", canonical: `${SITE.url}/items/${id}` },
      createdAt: publishedAt,
      updatedAt: publishedAt,
    };
    if (r.paper) base.paperFields = r.paper;
    if (r.project) base.projectFields = r.project;
    if (r.news) base.newsFields = r.news;
    base.score = computeScore(base);
    return base;
  });
}

export const ITEMS: Item[] = build();
